"""Task Boss

Revision ID: 3ba90715b052
Revises: 2244f27d94ba
Create Date: 2022-10-08 08:13:45.528929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba90715b052'
down_revision = '2244f27d94ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss_task',
    sa.Column('boss_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['boss.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boss_task')
    # ### end Alembic commands ###
