"""user tokens

Revision ID: 585467d58724
Revises: bb661d9384ef
Create Date: 2022-10-09 01:56:09.701712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585467d58724'
down_revision = 'bb661d9384ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
